version: "3.9"
services:
  userservice:
    build: .
    depends_on:
      - userservice-mysql-1
    ports:
      - "8081:8081"
    environment:
      DB_URL: userservice-mysql:3309/demo
      DB_USER: developer
      DB_PASS: password
  userservice-mysql-1:
    image: "mysql:latest"
    container_name: userservice-mysql
    volumes:
    - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_HOST: '%'
    ports:
      - "3309:3306"
volumes:
  db_mysql:

